### ISSUE TITLE
Error installing 5.1.0 in makefile

### ISSUE THREAD

**Issue by emgosa** [ibmdb/ruby-ibmdb#128]
Hi, i am using ruby 3.0.1 and rails 6.1.4.4 cant install latest version 5.2.0 due to rails version and getting this error in makefile

```Installing ibm_db 5.1.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext
/home/joker/.rbenv/versions/3.0.1/bin/ruby -I /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0 -r ./siteconf20220209-17778-3oilr2.rb extconf.rb
extconf.rb:70: warning: already initialized constant DOWNLOADLINK
extconf.rb:45: warning: previous definition of DOWNLOADLINK was here
extconf.rb:194: warning: already initialized constant IBM_DB_HOME
extconf.rb:21: warning: previous definition of IBM_DB_HOME was here
extconf.rb:196: warning: already initialized constant IBM_DB_INCLUDE
extconf.rb:177: warning: previous definition of IBM_DB_INCLUDE was here
extconf.rb:197: warning: already initialized constant IBM_DB_LIB
extconf.rb:178: warning: previous definition of IBM_DB_LIB was here
Detected 64-bit Ruby
 
Detected platform - linux x86 64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver
checking for SQLConnect() in -ldb2... yes
checking for gil_release_version.h... yes
checking for unicode_support_version.h... yes
creating Makefile
extconf.rb:306:in `libpathflag': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG
        from /home/joker/.rbenv/versions/3.0.1/lib/ruby/3.0.0/mkmf.rb:2297:in `create_makefile'
        from extconf.rb:322:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ibm_db-5.1.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0 for inspection.
Results logged to /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ibm_db-5.1.0/gem_make.out

  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:95:in `run'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/tempfile-0.1.2/lib/tempfile.rb:317:in `open'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:161:in `build_extension'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:192:in `each'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:853:in `build_extensions'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:204:in `install'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/worker.rb:62:in `apply_func'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/worker.rb:54:in `loop'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/worker.rb:54:in `process_queue'
  /home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.3.6/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing ibm_db (5.1.0), and Bundler cannot continue.

In Gemfile:
  ibm_db
```

here is mkmf.log

```have_library: checking for SQLConnect() in -ldb2... -------------------- yes

"gcc -o conftest -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/x86_64-linux -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0 -I. -I/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/include -I/home/joker/.rbenv/versions/3.0.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/joker/.rbenv/versions/3.0.1/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -L. -L/home/joker/.rbenv/versions/3.0.1/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -o conftest -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/x86_64-linux -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0 -I. -I/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/include -I/home/joker/.rbenv/versions/3.0.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/joker/.rbenv/versions/3.0.1/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -L. -L/home/joker/.rbenv/versions/3.0.1/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib -lruby -ldb2  -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:14:57: error: ‘SQLConnect’ undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                         ^~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"gcc -o conftest -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/x86_64-linux -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0 -I. -I/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/include -I/home/joker/.rbenv/versions/3.0.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/joker/.rbenv/versions/3.0.1/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/lib -L. -L/home/joker/.rbenv/versions/3.0.1/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/joker/.rbenv/versions/3.0.1/lib -L/home/joker/.rbenv/versions/3.0.1/lib -lruby -ldb2  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: extern void SQLConnect();
15: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

have_header: checking for gil_release_version.h... -------------------- yes

"gcc -E -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/x86_64-linux -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0 -I. -I/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/include -I/home/joker/.rbenv/versions/3.0.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <gil_release_version.h>
/* end */

--------------------

have_header: checking for unicode_support_version.h... -------------------- yes

"gcc -E -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/x86_64-linux -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0/ruby/backward -I/home/joker/.rbenv/versions/3.0.1/include/ruby-3.0.0 -I. -I/home/joker/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ibm_db-5.1.0/ext/../lib/clidriver/include -I/home/joker/.rbenv/versions/3.0.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <unicode_support_version.h>
/* end */

--------------------

```

**Comment by praveen-db2** [comment]
@emgosa we are not yet supported for Ruby 3.0.1, we are start working to support Ruby 3.1 and Rails 7.0.
Once we release it will fix your issues.

**Comment by emgosa** [comment]
@praveen-db2 do you know aproximately when it will be?

**Comment by praveen-db2** [comment]
@emgosa another 2 months, if any hiccups might take more as well.

**Comment by praveen-db2** [comment]
@emgosa can you check your env variables IBM_DB_xxxx. I think its not properly set. Or just try to unset it to nothing and try installing ibm_db again.

**Comment by praveen-db2** [comment]
@emgosa were you able to resolve this ?

**Comment by matthewkrom** [comment]
Hi, There is a similar issue that happens if `rubyzip` gem is not already installed in the environment. Especially, if /home/joker is not your own home path (in mine, I was seeing /home/rakhil or /home/rahkil or similar). It was exactly the same — the -I (.h include paths) were not correct, causing the first error to be "SQLConnect" undefined. So, you may want to try ensuring that you have gem rubyzip previously installed (`gem list rubyzip`).  (Mine is rubyzip 2.3.2)

**Comment by praveen-db2** [comment]
When I was creating setup for rails 6.1 on ruby 3.0, **zip** gem was missing hence I need to install it manually as in one of file IBM_DB_Adapter/ibm_db/ext/extconf.rb there is dependency of zip which is used to download clidriver, unzip to install the same. But rubyzip got auto installed as dependency of some other gem, I am not sure which is that. If clidriver is not installed we get undefined SQLconnect error. 

In next release of ruby_ibmdb which supports for Rails 6.1 I ill mandate zip gem as dependency so it get auto installed.

**Comment by praveen-db2** [comment]
@emgosa shall I close this issue, if it got resolved. ? 

I ill be including zip gem to install by default when ruby_ibmdb gem is installed.
