### ISSUE TITLE
ruby ds driver build fails on RHEL 7.9 for Db2 11.5.6

### ISSUE THREAD

**Issue by Anshu-Garg** [ibmdb/ruby-ibmdb#130]
steps followed from https://www.ibm.com/docs/en/db2/11.5?topic=rr-installing-db-ruby-driver-rails-adapter-as-ruby-gem

Environment information

```
[db2inst1@cps-rack-79-vm-147 dsdriver]$ env
DB2INSTANCE=db2inst1
XDG_SESSION_ID=18
IBM_DB_LIB=/home/db2inst1/sqllib/lib
HOSTNAME=cps-rack-79-vm-147
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
IBM_DB_DIR=/home/db2inst1/sqllib
OLDPWD=/home/db2inst1
USER=db2inst1
LD_LIBRARY_PATH=/home/db2inst1/dsdriver/lib:/home/db2inst1/dsdriver/./lib:/home/db2inst1/sqllib/lib64:/home/db2inst1/sqllib/lib64/gskit:/home/db2inst1/sqllib/lib32
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
IBM_DB_HOME=/home/db2inst1/dsdriver
DB2NODE=0
MAIL=/var/spool/mail/db2inst1
PATH=/home/db2inst1/dsdriver/./adm:/home/db2inst1/dsdriver/./bin:/home/db2inst1/.rbenv/plugins/ruby-build/bin:/home/db2inst1/.rbenv/shims:/home/db2inst1/.rbenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/db2inst1/.local/bin:/home/db2inst1/bin:/home/db2inst1/sqllib/bin:/home/db2inst1/sqllib/adm:/home/db2inst1/sqllib/misc:/home/db2inst1/sqllib/pd:/home/db2inst1/sqllib/gskit/bin:/home/db2inst1/sqllib/db2tss/bin
PWD=/home/db2inst1/dsdriver
JAVA_HOME=/opt/IBM/ibm-java-x86_64-80
LANG=en_US.UTF-8
RBENV_SHELL=bash
DB2_HOME=/home/db2inst1/sqllib
HISTCONTROL=ignoredups
SHLVL=1
HOME=/home/db2inst1
IBM_DB_INCLUDE=/home/db2inst1/sqllib/include
LOGNAME=db2inst1
CLASSPATH=/home/db2inst1/dsdriver/./tools/antlr-3.3-java.jar:/home/db2inst1/dsdriver/./tools/jline-0.9.93.jar:/home/db2inst1/dsdriver/./tools/clpplus.jar:/home/db2inst1/dsdriver/./java/sqlj4.zip:/home/db2inst1/dsdriver/./java/db2jcc4.jar:/home/db2inst1/sqllib/java/db2java.zip:/home/db2inst1/sqllib/java/sqlj4.zip:/home/db2inst1/sqllib/function:/home/db2inst1/sqllib/java/db2jcc_license_cu.jar:/home/db2inst1/sqllib/tools/clpplus.jar:/home/db2inst1/sqllib/tools/jline-0.9.93.jar:/home/db2inst1/sqllib/java/db2jcc4.jar:/home/db2inst1/sqllib/java/db2jcc_license_cisuz.jar:.
LESSOPEN=||/usr/bin/lesspipe.sh %s
DB2LIB=/home/db2inst1/sqllib/lib
_=/bin/env
```

```
[db2inst1@cps-rack-79-vm-147 dsdriver]$ gem --version
3.1.2
[db2inst1@cps-rack-79-vm-147 dsdriver]$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
```

output of install command

```
gem install ibm_db
Building native extensions. This could take a while...
ERROR:  Error installing ibm_db:
        ERROR: Failed to build gem native extension.

    current directory: /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ibm_db-5.2.0/ext
/myinst/.rbenv/versions/2.7.0/bin/ruby -I /myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0 -r ./siteconf20220328-22416-f775tu.rb extconf.rb
/myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- zip (LoadError)
        from /myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ibm_db-5.2.0 for inspection.
Results logged to /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/gem_make.out
```

log files generated

``` 
cat /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/mkmf.log
[db2inst1@cps-rack-79-vm-147 dsdriver]$ cat /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/mkmf.log
gil_release_version.h is:
/* begin */
1: #ifndef GIL_RELEASE_VERSION_H
2: #define GIL_RELEASE_VERSION_H
3: #endif
/* end */

unicode_support_version.h is:
/* begin */
1: #ifndef UNICODE_SUPPORT_VERSION_H
2: #define UNICODE_SUPPORT_VERSION_H
3: #endif
/* end */

have_library: checking for SQLConnect() in -ldb2... -------------------- yes

"gcc -o conftest -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-linux -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include -I/home/rakhil/.rbenv/versions/3.0.0/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/home/rakhil/.rbenv/versions/3.0.0/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -o conftest -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-linux -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include -I/home/rakhil/.rbenv/versions/3.0.0/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/home/rakhil/.rbenv/versions/3.0.0/lib -lruby -ldb2  -lm   -lc"
conftest.c: In function 't':
conftest.c:14:57: error: 'SQLConnect' undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                         ^~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-cast-function-type'
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"gcc -o conftest -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-linux -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include -I/home/rakhil/.rbenv/versions/3.0.0/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -L/home/rakhil/.rbenv/versions/3.0.0/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/.rbenv/versions/3.0.0/lib -L/home/rakhil/.rbenv/versions/3.0.0/lib -lruby -ldb2  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: extern void SQLConnect();
15: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

have_header: checking for gil_release_version.h... -------------------- yes

"gcc -E -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-linux -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include -I/home/rakhil/.rbenv/versions/3.0.0/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <gil_release_version.h>
/* end */

--------------------

have_header: checking for unicode_support_version.h... -------------------- yes

"gcc -E -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/x86_64-linux -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0/ruby/backward -I/home/rakhil/.rbenv/versions/3.0.0/include/ruby-3.0.0 -I. -I/work/rakhil/work_ruby/git_clone/5.2.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include -I/home/rakhil/.rbenv/versions/3.0.0/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <unicode_support_version.h>
/* end */

--------------------
```

output of log /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/gem_make.out

```
[db2inst1@cps-rack-79-vm-147 dsdriver]$ cat  /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/gem_make.out
current directory: /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ibm_db-5.2.0/ext
/myinst/.rbenv/versions/2.7.0/bin/ruby -I /myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0 -r ./siteconf20220328-22416-f775tu.rb extconf.rb
/myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- zip (LoadError)
        from /myinst/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /myinst/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ibm_db-5.2.0/mkmf.log

extconf failed, exit code 1
```

**Comment by praveen-db2** [comment]
@Anshu-Garg error thrown there is "`require': cannot load such file -- zip (LoadError)`"
Can you install zip gem like "`gem install zip`" and try "`gem install ibm_db`"

**Comment by praveen-db2** [comment]
Will close this as we already provided GEM file.
