### ISSUE TITLE
Fetch Failure: <error message could not be retrieved

### ISSUE THREAD

**Issue by styrken** [ibmdb/ruby-ibmdb#147]
Hi,

Sometimes we are getting this error. I can't figure out why. It only happens every other day and a simple refresh fixes the problem.

```
[90236708-e4f4-4368-b5ee-8be6e3c2d847] ActionView::Template::Error (: An unexpected error occurred during data retrieval: uncaught throw :"Fetch Failure: <error message could not be retrieved>"):
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     19:           <%= label_tag :responsible,nil, :class=>"control-label" %>
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     20:           <div class="control">
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     21:             <%= select_tag(:responsible,
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     22:                            options_from_collection_for_select(User.active.order(:name), :id, :name, :selected => session[:responsible]),
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     23:                            :include_blank => true, :class => "fancy-select live-submit span12") %>
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     24:           </div>
[90236708-e4f4-4368-b5ee-8be6e3c2d847]     25:         </div>
```

The failing line is 22 and I believe it is caused by `User.active.order(:name)`. The `active` scope is: `scope :active, -> { where(:active => true).order(:name) }`

I found the same error description here https://bitbucket.org/litmis/ruby-ibm_db/issues/1/fetch-column-metadata-error so I though it was something related to this gem or the db2-driver.

Any ideas?

**Comment by praveen-db2** [comment]
@styrken which version of ibm_db gem you are using ?

**Comment by praveen-db2** [comment]
@styrken please use latest gem release v 5.4.0, this issue is been fixed there.

**Comment by styrken** [comment]
@praveen-db2 Those are already set

IBM_DB_HOME=/data/dsdriver/ 
LD_LIBRARY_PATH=/data/dsdriver/lib

It's also printed in the log above.

**Comment by praveen-db2** [comment]
@styrken I don't see any log in your previous comments which sets these environment variables.

**Comment by praveen-db2** [comment]
@styrken you can uninstall ibm_db along with existing dsdriver and also unset the earlier said environment variables. And install latest ibm_db freshly, ibm_db gem auto installs dsdriver as well. Later you can set environment variables to path where ibm_db gem installs dsdriver.

**Comment by styrken** [comment]
Hi @praveen-db2 

I tried but get this error:

```
xtool@i25372:/data/apps/xtool-staging/dsv-xtool-v2 # gem install ibm_db -v 5.4.0
Building native extensions. This could take a while...
ERROR:  Error installing ibm_db:
        ERROR: Failed to build gem native extension.

    current directory: /home/xtool/.gem/ruby/gems/ibm_db-5.4.0/ext
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20230328-1153942-1f0vixf.rb extconf.rb
extconf.rb:70: warning: already initialized constant DOWNLOADLINK
extconf.rb:45: warning: previous definition of DOWNLOADLINK was here
extconf.rb:152:in `initialize': not in gzip format (Zlib::GzipFile::Error)
        from extconf.rb:152:in `open'
        from extconf.rb:152:in `untarCLIPackage'
        from extconf.rb:191:in `<main>'
Detected 64-bit Ruby

Detected platform - linux x86 64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/xtool/.gem/ruby/extensions/x86_64-linux/2.7.0/ibm_db-5.4.0/mkmf.log
```

Output of mentioned logfile:


```
gil_release_version.h is:
/* begin */
1: #ifndef GIL_RELEASE_VERSION_H
2: #define GIL_RELEASE_VERSION_H
3: #endif
/* end */

unicode_support_version.h is:
/* begin */
1: #ifndef UNICODE_SUPPORT_VERSION_H
2: #define UNICODE_SUPPORT_VERSION_H
3: #endif
/* end */

have_library: checking for SQLConnect() in -ldb2... -------------------- yes

LD_LIBRARY_PATH=.:/home/pnarayanappa/ROR31/ruby_exe/lib:/jre/lib:/jre/bin:/lib:/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/clidriver/lib/ "gcc -o conftest -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/x86_64-linux -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/ruby/backward -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0 -I. -I/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef conftest.c  -L. -L/home/pnarayanappa/ROR31/ruby_exe/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm   -lm  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

LD_LIBRARY_PATH=.:/home/pnarayanappa/ROR31/ruby_exe/lib:/jre/lib:/jre/bin:/lib:/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/clidriver/lib/ "gcc -o conftest -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/x86_64-linux -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/ruby/backward -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0 -I. -I/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef conftest.c  -L. -L/home/pnarayanappa/ROR31/ruby_exe/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm  -lc"
conftest.c: In function ‘t’:
conftest.c:14:57: error: ‘SQLConnect’ undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                         ^~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

LD_LIBRARY_PATH=.:/home/pnarayanappa/ROR31/ruby_exe/lib:/jre/lib:/jre/bin:/lib:/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/clidriver/lib/ "gcc -o conftest -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/x86_64-linux -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/ruby/backward -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0 -I. -I/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef conftest.c  -L. -L/home/pnarayanappa/ROR31/ruby_exe/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/pnarayanappa/ROR31/ruby_exe/lib -L/home/pnarayanappa/ROR31/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm  -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: extern void SQLConnect();
15: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

have_header: checking for gil_release_version.h... -------------------- yes

LD_LIBRARY_PATH=.:/home/pnarayanappa/ROR31/ruby_exe/lib:/jre/lib:/jre/bin:/lib:/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/clidriver/lib/ "gcc -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/x86_64-linux -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/ruby/backward -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0 -I. -I/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <gil_release_version.h>
/* end */

--------------------

have_header: checking for unicode_support_version.h... -------------------- yes

LD_LIBRARY_PATH=.:/home/pnarayanappa/ROR31/ruby_exe/lib:/jre/lib:/jre/bin:/lib:/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/clidriver/lib/ "gcc -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/x86_64-linux -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0/ruby/backward -I/home/pnarayanappa/ROR31/ruby_exe/include/ruby-3.1.0 -I. -I/home/pnarayanappa/ROR31/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wundef   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <unicode_support_version.h>
/* end */

--------------------

extconf failed, exit code 1

Gem files will remain installed in /home/xtool/.gem/ruby/gems/ibm_db-5.4.0 for inspection.
Results logged to /home/xtool/.gem/ruby/extensions/x86_64-linux/2.7.0/ibm_db-5.4.0/gem_make.out

```

**Comment by praveen-db2** [comment]
@styrken released new gem v 5.4.1 please use it. Before installing please unset any env variables u set like IBM_DB_HOME, LD_LIBRARY_PATH etc... anything specific to this gem.

**Comment by praveen-db2** [comment]
@styrken I think you are using older version of rails. Use rails version 7.0.4.

**Comment by styrken** [comment]
Okay, i can't upgrade right now

**Comment by praveen-db2** [comment]
@styrken will close this issue for now. If you find any issues further please feel free to reopen the same.
