### ISSUE TITLE
using ibm_db2 along with postgres is causing a problem with rails db:migrate

### ISSUE THREAD

**Issue by oeil2lynx** [ibmdb/ruby-ibmdb#174]
I have another connector ti Postgre and when I run rails db:migrate I have an error
```
root@b78c379556d4:/app# rails db:migrate:client
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.2.2/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.2.2/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.2.2/lib/net/protocol.rb:541: warning: previous definition of Socket was here
== 20240730100805 CreateBankReject: migrating =================================
-- create_table(:bank_rejects)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `puts_log' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x000055cb47fcd920>
/app/db/migrate/20240730100805_create_bank_reject.rb:3:in `change'

Caused by:
NoMethodError: undefined method `puts_log' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x000055cb47fcd920>
/app/db/migrate/20240730100805_create_bank_reject.rb:3:in `change'
Tasks: TOP => db:migrate:client
(See full trace by running task with --trace)
root@b78c379556d4:/app#
```

**Comment by praveen-db2** [comment]
@oeil2lynx can you please provide call stack, want to know which api from ibm_db is causing issue.

**Comment by bimalkjha** [comment]
@oeil2lynx Could you please share the requested information? Thanks.

**Comment by oeil2lynx** [comment]
Sorry I wasn't connected for a long time, I try to do this soon

**Comment by bimalkjha** [comment]
closing issue as of now. Once you share the requested data, we can reopen it. thanks.
