### ISSUE TITLE
Missing method 'columns'

### ISSUE THREAD

**Issue by onordgren** [ibmdb/ruby-ibmdb#21]
Hello, I just updated my version of rails to 3.2.17 from 3.2.13 and on my production server I now run into the following error when using the method pluck. Im running ibm_db v 2.5.18.

```
undefined method `columns' for #<IBM_DB::Statement:0x0000000569b2e8>
```

The code that it run is 

```
Candidature.pluck(:name)...
```

Any clues on what might be causing this?

And with the following framework trace

```
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/relation/calculations.rb:185:in `pluck'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `call'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `block in capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:608:in `with_haml_buffer'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:364:in `capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:104:in `content_tag_for_single_record'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:89:in `content_tag_for'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:351:in `block in collection_with_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `each'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `collection_with_template'
vendor/bundle/ruby/1.9.1/gems/multi_fetch_fragments-0.0.17/lib/multi_fetch_fragments.rb:75:in `render_collection_with_multi_fetch_cache'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:234:in `block in render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:233:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:41:in `render_partial'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:15:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/rendering_helper.rb:24:in `render'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `call'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `block in capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:608:in `with_haml_buffer'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:364:in `capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:104:in `content_tag_for_single_record'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:89:in `content_tag_for'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:351:in `block in collection_with_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `each'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `collection_with_template'
vendor/bundle/ruby/1.9.1/gems/multi_fetch_fragments-0.0.17/lib/multi_fetch_fragments.rb:75:in `render_collection_with_multi_fetch_cache'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:234:in `block in render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:233:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:41:in `render_partial'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/rendering_helper.rb:27:in `render'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `call'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:368:in `block in capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:608:in `with_haml_buffer'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:364:in `capture_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:104:in `content_tag_for_single_record'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/record_tag_helper.rb:89:in `content_tag_for'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:351:in `block in collection_with_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `each'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:348:in `collection_with_template'
vendor/bundle/ruby/1.9.1/gems/multi_fetch_fragments-0.0.17/lib/multi_fetch_fragments.rb:57:in `render_collection_with_multi_fetch_cache'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:234:in `block in render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/partial_renderer.rb:233:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:41:in `render_partial'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:15:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/rendering_helper.rb:24:in `render'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'
vendor/bundle/ruby/1.9.1/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in `block in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:18:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:36:in `render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:17:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:110:in `_render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/streaming.rb:225:in `_render_template'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:103:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:88:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
vendor/ruby-1.9.3/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/core_ext/benchmark.rb:5:in `ms'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:39:in `render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/responder.rb:232:in `default_render'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/responder.rb:160:in `to_html'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/responder.rb:153:in `respond'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/responder.rb:146:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/mime_responds.rb:239:in `respond_with'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:491:in `_run__453186150088593794__process_action__4550856987894487656__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:246:in `block in action'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
vendor/bundle/ruby/1.9.1/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__3816171830721382793__call__2590470846085509166__callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `block in call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/static.rb:63:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
vendor/bundle/ruby/1.9.1/bin/thin:23:in `load'
vendor/bundle/ruby/1.9.1/bin/thin:23:in `<main>'
´´´
```

**Comment by arvindgu** [comment]
I have tested with *rails console* and I see ActiveRecord's pluck method is working fine. Could you please share your use case that reproduces this error.

**Comment by leonsp** [comment]
The codebase I'm looking at is currently on: 

* rails (3.2.21)
* activerecord (3.2.21)

**Comment by akhilravuri1** [comment]
Please feel free to reopen the issue if you are facing this with the latest driver.
