### ISSUE TITLE
rake db:migrate fails when using this gem with mysql

### ISSUE THREAD

**Issue by thd-rental-team** [ibmdb/ruby-ibmdb#31]
We have a situation where we have an existing codebase using mysql. We need to talk to an IBM DB2 database but have chosen not to use the activerecord adapter, instead calling the IBM_DB class directly.

I noticed the ibm_db adapter code is being called even though I have not configured my app to talk to ibm db via activerecord. How can the two work together?

Running a migration which creates a table yields the following:

```
$ RAILS_ENV=test bundle exec rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20150602202032 CreateRecoverAppActionLogs: migrating =======================
-- create_table(:recover_app_action_logs)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `has_key?' for "int(11) auto_increment PRIMARY KEY":String/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.26-universal-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:517:in `column'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:115:in `primary_key'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:199:in `create_table'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `create_table'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/username/workspace/app/db/migrate/20150602202032_create_table.rb:3:in `change'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/username/.rbenv/versions/2.1.6/bin/rake:23:in `load'
/Users/username/.rbenv/versions/2.1.6/bin/rake:23:in `<main>'
NoMethodError: undefined method `has_key?' for "int(11) auto_increment PRIMARY KEY":String
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.26-universal-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:517:in `column'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:115:in `primary_key'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:199:in `create_table'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `create_table'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/username/workspace/app/db/migrate/20150602202032_create_table.rb:3:in `change'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/username/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/username/.rbenv/versions/2.1.6/bin/rake:23:in `load'
/Users/username/.rbenv/versions/2.1.6/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by arvindgu** [comment]
You will need to customize ibm_db the gem for your requirements. To prevent loading of  ibm activerecord adapter, you can try commenting below lines present under <i>IBM_DB_Adapter\ibm_db\lib\IBM_DB.rb</i> file.
<i>require 'active_record'
require 'active_record/connection_adapters/ibm_db_adapter'
</i>

To talk to IBM DB2 database directly, your application code will need to call the IBM_DB_Driver APIs present in <i>IBM_DB_Driver/ibm_db.c</i> file.

**Comment by thd-rental-team** [comment]
Thanks Arvind.

Just to follow on with this conversation, I have create a repository which highlights the problem we are having.

https://github.com/thd-rental/rails-db2-mysql

**Comment by arvindgu** [comment]
Refer #32

**Comment by thd-rental-team** [comment]
We just verified that this bug is still present in v2.6.1

```
 |2.2.2| nostrand in ~/workspace/rails-db2-mysql
± cs+ab |master ✗| → rake db:migrate
== 20150608133656 CreateATable: migrating =====================================
-- create_table(:a_tables)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `has_key?' for "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL":String/Users/pivotal/workspace/rails-db2-mysql/db/migrate/20150608133656_create_a_table.rb:3:in `change'
-e:1:in `<main>'
NoMethodError: undefined method `has_key?' for "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL":String
/Users/pivotal/workspace/rails-db2-mysql/db/migrate/20150608133656_create_a_table.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)


```

**Comment by thd-rental-team** [comment]
@arvindgu @praveend I would say that this issue is not closed.  Can we keep the issue open until we can use the ibm_db gem with mysql as well as DB2?

Also, we would like to escalate this issue but the people with the IBM support account credentials are many teams away from us.  Is there any way that you can escalate this on your side?

Thanks, 
Adam Berlin @ Pivotal

**Comment by berlin-ab** [comment]
@arvindgu @praveend This issue is not closed.  It is caused mostly by the fact that the IBM DB gem monkey-patches ActiveRecord instead of using its extension points.

By extending AR classes for IBM_DB's purposes, the other AR adapters are left untouched.  Please implement *some* change that allows multiple IBM adapters to function simultaneously.

Thanks,
Adam Berlin @ Pivotal

**Comment by jonstorer** [comment]
@arvindgu +1

I'm attempting to use this gem with postgresql.

**Comment by gkemmey** [comment]
Did anyone come up with a workaround for connecting to both DB2 and MySQL, or is the recommendation still to hand-edit the gem files?

**Comment by berlin-ab** [comment]
The recommendation is to submit a pull request that replaces monkey patching with subclassing. We introduced this patch locally and were able to get the two working side-by-side. Our team switched to jruby and used the java drivers as a work-around.
