### ISSUE TITLE
version 3.0.4 is not working in Mac (Library not loaded: libdb2.dylib)

### ISSUE THREAD

**Issue by tsathishkumar** [ibmdb/ruby-ibmdb#68]
Hi,
First of all the libraries are not being shipped with the gem when I installed the gem(I was expecting them to be present under `$GEM_HOME/ibm_db-*/lib/clidriver`). 

So, I followed the steps below
1. Downloaded the libraries from [http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz](url)  
2. Set the environment variable `$export DYLD_LIBRARY_PATH=/Users/tsathish/Downloads/clidriver/lib`
3. Tried to load ibm_db in irb

```
$ irb 
2.2.3 :001 > require 'ibm_db'
LoadError: dlopen(/Users/tsathish/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/lib/ibm_db.bundle, 9): Library not loaded: libdb2.dylib
  Referenced from: /Users/tsathish/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/lib/ibm_db.bundle
  Reason: unsafe use of relative rpath libdb2.dylib in /Users/tsathish/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/lib/ibm_db.bundle with restricted binary - /Users/tsathish/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/lib/ibm_db.bundle
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /Users/tsathish/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/lib/ibm_db.rb:18:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from (irb):1
    from /usr/bin/irb:12:in `<main>'
```

Please let me know if I'm missing something here.

Thanks in advance.

**Comment by arvindgu** [comment]
The ibm_db gem auto downloads the macos64_odbc_cli.tar.gz and configure the libraries. 

I recommend to delete the by uninstall ibm_db gem command and ensure that all the files and folder of ibm_db gem are deleted in the file system. Then try installing it with "sudo". if the problem still persists, reopen this.
