### ISSUE TITLE
rake db:create failed

### ISSUE THREAD

**Issue by Hareramrai** [ibmdb/ruby-ibmdb#70]
Hi , 

I am not able to run the rake db:create command. 

````
rake db:create
Rake tasks not supported by 'ibm_db' adapter
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:263:in `class_for_adapter'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:93:in `create'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:274:in `each'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/hareram/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/hareram/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
./bin/rake:4:in `<main>'
Couldn't create database for {"adapter"=>"ibm_db", "username"=>"db2inst1", "password"=>"password", "database"=>"blog_dev"}
Rake tasks not supported by 'ibm_db' adapter

````

Could you please help me on this. 

Thanks,
Hare

**Comment by Hareramrai** [comment]
is this gem obsoleted ?

**Comment by arvindgu** [comment]
Hi Hareramrai, the gem is not obsolete.
The ibm_dn gem do not support rake task . You can create a database. in DB2 and connect to it.
