### ISSUE TITLE
Error on downloading IBM DB Driver

### ISSUE THREAD

**Issue by Accenture012** [ibmdb/ruby-ibmdb#82]
Hi,
when i try to install the gem i receive the follow error:

```
Installing ibm_db 3.0.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/pamuser/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4/ext
/home/pamuser/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20181105-7416-1qx5w4p.rb extconf.rb
extconf.rb:68: warning: already initialized constant DOWNLOADLINK
extconf.rb:44: warning: previous definition of DOWNLOADLINK was here
extconf.rb:125:in `initialize': not in gzip format (Zlib::GzipFile::Error)
	from extconf.rb:125:in `open'
	from extconf.rb:125:in `untarCLIPackage'
	from extconf.rb:161:in `<main>'
Detected 64-bit Ruby
 
Detected platform - linux x86 64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver

extconf failed, exit code 1

Gem files will remain installed in /home/pamuser/.rvm/gems/ruby-2.2.3@backoffice-adapter/gems/ibm_db-3.0.4 for inspection.
Results logged to /home/pamuser/.rvm/gems/ruby-2.2.3@backoffice-adapter/extensions/x86_64-linux/2.2.0/ibm_db-3.0.4/gem_make.out

An error occurred while installing ibm_db (3.0.4), and Bundler cannot continue.
Make sure that `gem install ibm_db -v '3.0.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  ibm_db
```

If i try to download manually the driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli address i receive a 500 Internal Server Error.
Any advice?

Thanks

**Comment by akhilravuri1** [comment]
Hi @Accenture012 

we have released the new version for ibm_db.

Installing the new version will solve the issue.

closing the issue...if you face any issues in the latest version please feel free to open a new issue.

Thanks,
Akhil

**Comment by dgbtech** [comment]
Having same issue with versions 4.0.0 and 5.2.0
